version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - unconvert
    - unparam
    - nolintlint
  settings:
    misspell:
      locale: US
    nolintlint:
      require-explanation: true
      require-specific: true

issues:
  max-issues-per-linter: 50
  max-same-issues: 5

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/agynio/gh-pr-review
